joint:
  names: [singleFinger, doubleFinger]
motion:
  names: [right, zero]
  right:
    step: [-2048, 2048]  # 2048 per pi
    time_from_start: 2.0  # sec
  zero:
    step: [2048, -2048]
    time_from_start: 4.0

